# Generated by Django 5.0.8 on 2024-08-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_type", models.CharField(max_length=100)),
                ("asset_loc", models.CharField(max_length=100)),
                ("thumbnail_loc", models.CharField(max_length=100)),
                ("asset_desc", models.CharField(max_length=100)),
            ],
        ),
    ]
